### ISSUE TITLE
Network Error / Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by leochras** [SchoolUtils/WebUntis#57]
I am trying to use the WebUntis API in a React Native / TypeScript project on Stackblitz, but it keeps throwing this network error and I have no clue why.

![image](https://user-images.githubusercontent.com/16163571/149623935-72b31bc9-74dd-45cf-adf8-aa8b962db6b4.png)

I don't know if this has to do with the API, because I am new to react and APIs, so any help would be appreciated.

**Comment by TheNoim** [comment]
This is not an issue with WebUntis or the API itself. This is how Content Security in browsers work. You can't access api routes from a foreign host except if he allows it. However, you can try to set https://github.com/SchoolUtils/WebUntis/blob/master/index.js#L25 manual and add a CORS proxy. 

For example (untested):

```javascript
// untis is your untis api instance
untis.baseurl = "https://crossorigin.me/" + untis.baseurl;
```

**Comment by leochras** [comment]
Thank you for the answer. 

I am setting the base URL here (which should be the same, right?):
![image](https://user-images.githubusercontent.com/16163571/149626119-4c3bb8a9-2fdb-4630-85f8-adbda9b6878a.png)

Unfortunately, I still get the same error when using crossorigin.

It works with mese.webuntis.com when I use it locally with node, so I don't know what's wrong here.

**Comment by leochras** [comment]
Oops, the first[]( https:// )shouldn't be there..

**Comment by TheNoim** [comment]
I could provide an option which disables the user agent.

**Comment by leochras** [comment]
That would be great but would that fix my issue? Because I don't know what to do at that point..

**Comment by TheNoim** [comment]
> That would be great but would that fix my issue? Because I don't know what to do at that point..

I can't promise it. But maybe it will. At least it will fix the User Agent error.

**Comment by TheNoim** [comment]
I published a new version with the `disableUserAgent` option:

![Screenshot 2022-01-16 at 01 12 51](https://user-images.githubusercontent.com/5133056/149642177-60cc12cd-7308-4beb-98ac-57f7c5dfca29.png)

**Comment by leochras** [comment]
I appreciate the effort! But for me, it didn't fix the problem. Neither with crossorigin nor without.

**Comment by TheNoim** [comment]
Which problem still persist?

**Comment by TheNoim** [comment]
Or better, can you provide a project for reproduction?

**Comment by leochras** [comment]
I still get these errors:
![image](https://user-images.githubusercontent.com/16163571/149667838-3d1c2ac3-07c6-46b2-a7c3-7ab15e20a16a.png)

This is what the console on stackblitz says:
![image](https://user-images.githubusercontent.com/16163571/149667975-1abc2ce8-3e92-4597-ade2-a9aa7543ef34.png)

Here's my code, broken down to the bare minimum:

`import React, { Component } from 'react';
import { render } from 'react-dom';
import Hello from './Hello';
import './style.css';

const WebUntis = require('webuntis');

interface AppProps {}
interface AppState {
  endTime: string;
}

const untis = new WebUntis(
  'htbla_kaindorf',
  'traley17',
  't&BpMsJd6q#p',
  'mese.webuntis.com/',
  'Stackblitz',
  'true'
);

let endTime: string;
let day = new Date(2022, 0, 17);

async function getLastLesson(day: Date) {
  console.log('getLastLesson');
  try {
    await untis
      .login()
      .then(() => {
        console.log('1');
        return untis.getOwnTimetableForRange(day, day);
      })
      .then((timetable) => {
        timetable.sort((a, b) => a.startTime - b.startTime);
        let endTime = WebUntis.convertUntisTime(
          timetable[timetable.length - 1].endTime,
          new Date()
        );
        return endTime;
      })
      .then((endTime) => {
        try {
          console.log('Success');
          console.log(endTime);
        } catch (error) {
          endTime = 'Error';
          console.log(error);
        }
      });
  } catch (error) {
    console.log(error);
  }
}

getLastLesson(day);

class App extends Component<AppProps, AppState> {
  constructor(props) {
    super(props);
    this.state = {
      endTime: endTime,
    };
  }

  render() {
    return (
      <div>
        <p>Last lesson is at: {this.state.endTime}</p>
      </div>
    );
  }
}

render(<App />, document.getElementById('root'));
`

**Comment by TheNoim** [comment]
But why are you not using the crossorigin proxy anymore? Without it, it will never work inside of a web browser.

**Comment by leochras** [comment]
With crosorigin:

![image](https://user-images.githubusercontent.com/16163571/149668341-4ae07f78-1fe9-4bf7-a512-c809c0601833.png)

**Comment by leochras** [comment]
I also tried two other CORS proxies (thingproxy and alloworigin) but that only made it worse.

**Comment by TheNoim** [comment]
Ok, I tested it locally and now I know what the issue is. It seems like there is no good public available CORS proxy anymore. Most of them faced too much abuse. You now have only two options: 

1. Host your own CORS proxy and use it instead of crossorigin.me. crossorigin.me doesn't even exist anymore, this is why the request fails. You can use this https://github.com/Rob--W/cors-anywhere to setup your own CORS proxy
2. You do all WebUntis requests on server side with nodejs

**Comment by TheNoim** [comment]
> I also tried two other CORS proxies (thingproxy and alloworigin) but that only made it worse.

Most of them get disqualified, because they do not support everything what webuntis needs https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347

**Comment by leochras** [comment]
Well, that's sad. I don't think these solutions are right for me, as I don't have the option to self-host. But thank you for everything!

**Comment by TheNoim** [comment]
When somebody ever needs this: 

I tested a local version of https://github.com/Rob--W/cors-anywhere This works fine. 

To make it work with http for local testing, you need to do this

```javascript
// Untis instance
untis.baseurl = `http://` + YOUR_BASE_URL;
// Update the axios instance
untis.axios = untis.axios.create({ baseURL: untis.baseurl });
```
